; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Sistema Boletas POS"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "PablitoPOS"
#define MyAppExeName "SistemaBoletasPOS.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A5908642-1234-5678-9ABC-DEF012345678}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=installer
OutputBaseFilename=SistemaBoletasPOS_Installer
SetupIconFile=logo.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
WizardSmallImageFile=wizard_small_cyberpunk.png
WizardImageFile=wizard_cyberpunk.png

[Languages]
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; The main executable from the dist folder
Source: "dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; Include the logo/icon if needed for the app directory (though embedded in exe, sometimes good to have)
Source: "logo.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "logo.png"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Dirs]
; Rutas de datos en APPDATA. Se preservan en desinstalación.
Name: "{userappdata}\PablitoPOS"; Flags: uninsneveruninstall
Name: "{userappdata}\PablitoPOS\boletas"; Flags: uninsneveruninstall
Name: "{userappdata}\PablitoPOS\backups"; Flags: uninsneveruninstall
Name: "{userappdata}\PablitoPOS\recovery"; Flags: uninsneveruninstall
Name: "{userappdata}\PablitoPOS\runtime_plain\current"; Flags: uninsneveruninstall

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
// Copia DB legacy (si existiera junto al exe) hacia APPDATA\PablitoPOS\runtime_plain\current\boletas.sqlite3
procedure CurStepChanged(CurStep: TSetupStep);
var
	LegacyDb, TargetDb, TargetDir: string;
begin
	if CurStep = ssInstall then
	begin
		LegacyDb := ExpandConstant('{app}\boletas.sqlite3');
		TargetDir := ExpandConstant('{userappdata}\PablitoPOS\runtime_plain\current');
		TargetDb := TargetDir + '\\boletas.sqlite3';

		if FileExists(LegacyDb) and (not FileExists(TargetDb)) then
		begin
			if not DirExists(TargetDir) then
				ForceDirectories(TargetDir);
			try
				FileCopy(LegacyDb, TargetDb, False);
			except
				// Si falla, continuar sin bloquear la instalación
			end;
		end;
	end;
end;
