-- Esquema para Supabase (PostgreSQL)

CREATE TABLE company_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    ruc TEXT,
    address TEXT,
    phone TEXT,
    email TEXT,
    website TEXT,
    footer_message TEXT,
    logo_path TEXT,
    brand_color TEXT DEFAULT '#1f77b4',
    is_active INTEGER DEFAULT 1,
    yape_qr_path TEXT,
    include_igv INTEGER DEFAULT 1
);

CREATE TABLE clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni TEXT,
    full_name TEXT,
    phone TEXT,
    email TEXT,
    address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT,
    name TEXT,
    unit TEXT,
    price REAL,
    active INTEGER DEFAULT 1,
    stock INTEGER DEFAULT 0,
    price_includes_igv INTEGER DEFAULT 0
);

CREATE TABLE sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series TEXT,
    number INTEGER,
    datetime TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    client_id BIGINT REFERENCES clients(id),
    company_id BIGINT REFERENCES company_profile(id) DEFAULT 1,
    subtotal REAL,
    igv REAL,
    total REAL,
    pdf_path TEXT,
    serial_seguridad TEXT UNIQUE,
    discount REAL DEFAULT 0,
    is_proforma INTEGER DEFAULT 0,
    is_boletin INTEGER DEFAULT 0,
    is_adelanto INTEGER DEFAULT 0,
    advance_amount REAL DEFAULT 0,
    estimated_total REAL DEFAULT 0
);

CREATE TABLE sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT REFERENCES sales(id),
    product_id BIGINT REFERENCES products(id),
    description TEXT,
    unit TEXT,
    quantity REAL,
    unit_price REAL,
    subtotal REAL,
    discount REAL DEFAULT 0,
    discount_type TEXT DEFAULT 'fixed'
);

CREATE TABLE fiados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE,
    client_id BIGINT REFERENCES clients(id),
    status TEXT DEFAULT 'pendiente',
    total_bruto REAL DEFAULT 0,
    total_pagado REAL DEFAULT 0,
    total_pendiente REAL DEFAULT 0,
    pdf_path TEXT,
    sale_id BIGINT REFERENCES sales(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE fiado_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fiado_id BIGINT REFERENCES fiados(id),
    product_id BIGINT REFERENCES products(id),
    description TEXT,
    quantity REAL,
    unit TEXT,
    unit_price REAL,
    subtotal REAL,
    block TEXT,
    status TEXT DEFAULT 'pendiente',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    action TEXT NOT NULL,
    detail TEXT,
    user_pc TEXT
);

CREATE TABLE settings (
    key TEXT PRIMARY KEY,
    value TEXT
);

-- Datos iniciales
INSERT INTO settings (key, value) VALUES ('admin_pin', '1234') ON CONFLICT DO NOTHING;
INSERT INTO settings (key, value) VALUES ('customer_screen_index', '0') ON CONFLICT DO NOTHING;
INSERT INTO settings (key, value) VALUES ('onboarding_completed', '0') ON CONFLICT DO NOTHING;
