-- ==========================================
-- ESQUEMA MEJORADO PARA SUPABASE (POSTGRES)
-- ==========================================

-- ⚠️ PRECAUCIÓN: Las siguientes líneas borrarán las tablas existentes para que puedas empezar en limpio.
DROP TABLE IF EXISTS fiado_items CASCADE;
DROP TABLE IF EXISTS fiados CASCADE;
DROP TABLE IF EXISTS sale_items CASCADE;
DROP TABLE IF EXISTS sales CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS clients CASCADE;
DROP TABLE IF EXISTS company_profile CASCADE;
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS settings CASCADE;

-- Creación de Tablas
CREATE TABLE company_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    ruc TEXT,
    address TEXT,
    phone TEXT,
    email TEXT,
    website TEXT,
    footer_message TEXT,
    logo_path TEXT,
    brand_color TEXT DEFAULT '#1f77b4',
    is_active BOOLEAN DEFAULT TRUE,
    yape_qr_path TEXT,
    include_igv BOOLEAN DEFAULT TRUE,
    sol_user TEXT DEFAULT 'MODDATOS',
    sol_pass TEXT DEFAULT 'MODDATOS',
    cert_pem TEXT,
    production BOOLEAN DEFAULT FALSE,
    tax_regime TEXT DEFAULT 'nrus',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni TEXT UNIQUE,
    full_name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX idx_clients_dni ON clients(dni);
CREATE INDEX idx_clients_name ON clients(full_name);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE,
    name TEXT NOT NULL,
    unit TEXT,
    price DECIMAL(10,2) NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    stock INTEGER DEFAULT 0,
    price_includes_igv BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX idx_products_code ON products(code);
CREATE INDEX idx_products_name ON products(name);

CREATE TABLE sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series TEXT NOT NULL,
    number BIGINT NOT NULL,
    datetime TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    client_id BIGINT REFERENCES clients(id),
    company_id BIGINT REFERENCES company_profile(id) DEFAULT 1,
    subtotal DECIMAL(10,2) NOT NULL,
    igv DECIMAL(10,2) NOT NULL,
    total DECIMAL(10,2) NOT NULL,
    pdf_path TEXT,
    serial_seguridad TEXT UNIQUE,
    discount DECIMAL(10,2) DEFAULT 0,
    is_proforma BOOLEAN DEFAULT FALSE,
    is_boletin BOOLEAN DEFAULT FALSE,
    is_adelanto BOOLEAN DEFAULT FALSE,
    advance_amount DECIMAL(10,2) DEFAULT 0,
    estimated_total DECIMAL(10,2) DEFAULT 0
);
CREATE INDEX idx_sales_datetime ON sales(datetime);
CREATE INDEX idx_sales_series_number ON sales(series, number);

CREATE TABLE sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT REFERENCES sales(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id),
    description TEXT NOT NULL,
    unit TEXT,
    quantity DECIMAL(10,2) NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,
    subtotal DECIMAL(10,2) NOT NULL,
    discount DECIMAL(10,2) DEFAULT 0,
    discount_type TEXT DEFAULT 'fixed'
);
CREATE INDEX idx_sale_items_sale_id ON sale_items(sale_id);

CREATE TABLE fiados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE,
    client_id BIGINT REFERENCES clients(id),
    status TEXT DEFAULT 'pendiente',
    total_bruto DECIMAL(10,2) DEFAULT 0,
    total_pagado DECIMAL(10,2) DEFAULT 0,
    total_pendiente DECIMAL(10,2) DEFAULT 0,
    pdf_path TEXT,
    sale_id BIGINT REFERENCES sales(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE fiado_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fiado_id BIGINT REFERENCES fiados(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id),
    description TEXT,
    quantity DECIMAL(10,2),
    unit TEXT,
    unit_price DECIMAL(10,2),
    subtotal DECIMAL(10,2),
    block TEXT,
    status TEXT DEFAULT 'pendiente',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    action TEXT NOT NULL,
    detail TEXT,
    user_pc TEXT
);

CREATE TABLE settings (
    key TEXT PRIMARY KEY,
    value TEXT
);

-- Datos iniciales
INSERT INTO settings (key, value) VALUES ('admin_pin', '1234') ON CONFLICT DO NOTHING;
INSERT INTO settings (key, value) VALUES ('customer_screen_index', '0') ON CONFLICT DO NOTHING;
INSERT INTO settings (key, value) VALUES ('onboarding_completed', '0') ON CONFLICT DO NOTHING;
